# BinX AI & ML Internship
## Day 4 - Pandas: Tabular Data

Topics covered:
- Series vs DataFrame
- Loading and inspecting data
- Selecting and filtering
- Cleaning data
- Grouping and aggregation

### Step 1: Why Pandas?

**The problem:** Imagine a manager sends you a CSV file with employee 
data (name, age, salary, department) and asks: what's the average 
salary? How many employees per department? Are there missing values? 
Doing this with plain Python lists means writing loops for every single 
question  slow and repetitive.

**Why isn't NumPy enough on its own?** NumPy makes numeric operations 
very fast, but it only understands raw numbers arranged in a matrix. It 
has no concept of column names  it can't tell that one column is "Age" 
and another is "Salary". That makes it a poor fit for real-world tabular 
data with mixed types (text and numbers together).

**Where Pandas fits in:** Pandas is built on top of NumPy, but adds what 
NumPy is missing: labeled columns, row indexes, and the ability to mix 
data types in one table. It's designed specifically for tabular data - 
the format that CSV files, Excel sheets, SQL query results, JSON, and 
APIs typically come in.

**Where the name comes from:** Despite the panda-bear logo, the name 
actually comes from "**panel data**"  an econometrics term for datasets 
with multiple observations over time or across groups. Over time, Pandas 
became the standard tool for tabular data in general, not just panel 
data specifically.

**The two core objects:**
- **Series** : a single labeled column
- **DataFrame** : a full table made of multiple Series (columns) together

**Where Pandas sits:**

Python → NumPy → Pandas → Scikit-learn / TensorFlow / PyTorch

**A typical data project follows this flow:**

Load (CSV/Excel) → Explore → Clean → Feature Engineering → Visualize → Model

Pandas always comes *before* modeling, because a model can't work with 
messy or unstructured data - that cleanup step is exactly what Pandas is 
built for.

### Step 2:What is a Series?

A Series is a one dimensional labeled array  similar to a single column in an Excel sheet.

It can store:
- Numeric data
- Strings
- Boolean values
- Other Python objects

Unlike a Python list or NumPy array, a Series contains:
- Values
- Index labels

A Series is similar to a single column in a spreadsheet or database table.

### Step 3: Creating Pandas Series

Pandas provides multiple ways to create a Series depending on the source of data.

 We will explore the main methods for creating a Series:

1. Creating a Series from a Python List
2. Creating a Series from a NumPy Array
3. Creating a Series from a Python Dictionary
4. Creating an Empty Series
5. Creating a Series with Custom Index
6. Creating a Series with a Scalar Value
7. Creating a Series from a Range of Values
8. Creating a Series with Specific Data Type (`dtype`)
9. Creating a Named Series

These different approaches are useful depending on the structure and source of the data.

#### 1. Creating a Series from a Python List

A Python list is one of the simplest ways to create a Pandas Series.

Each element in the list becomes a value in the Series, and Pandas automatically creates a default numerical index starting from 0.

In [1884]:
import pandas as pd

_list = [1,2,3,4,5]
# Create a Pandas Series by converting a Python list into a one-dimensional labeled array _series = pd.Series(_list)
_series = pd.Series(_list)

_series 

# Display the Series object.
# In Jupyter Notebook, writing the variable name alone automatically shows its content. _series

0    1
1    2
2    3
3    4
4    5
dtype: int64

#### 2. Creating a Series from a NumPy Array

A Series can be created directly from a NumPy array.

This is common in data science workflows because NumPy is the foundation for numerical computation in Python.

In [1885]:
import numpy as np

arr = np.array([5, 10, 15, 20])

series = pd.Series(arr)

series

0     5
1    10
2    15
3    20
dtype: int64

#### 3. Creating a Series from a Dictionary

When a dictionary is used to create a Series:

- Dictionary keys become the Series index.
- Dictionary values become the Series data.

This is useful when we already have labeled data.

In [1886]:
student_scores = {
    "Ali": 90,
    "Sara": 85,
    "Omar": 95
}

scores = pd.Series(student_scores)

scores

Ali     90
Sara    85
Omar    95
dtype: int64

#### 4. Creating an Empty Series

An empty Series contains no values.

It can be useful when creating a Series that will be filled later.

In [1887]:
empty_series = pd.Series()

empty_series

Series([], dtype: object)

#### 5. Creating a Series with Custom Index

By default, Pandas creates integer indexes.

We can provide our own labels using the `index` parameter.

In [1888]:
values = [100, 200, 300]

sales = pd.Series(
    values,
    index=["January", "February", "March"]
)

sales

January     100
February    200
March       300
dtype: int64

#### 6. Creating a Series from a Scalar Value

A single value can be repeated to create a Series.

When using a scalar value, we must provide an index because Pandas does not know how many elements are needed.

In [1889]:
series = pd.Series(
    7,
    index=["A", "B", "C", "D"]
)

series

A    7
B    7
C    7
D    7
dtype: int64

#### 7. Creating a Series using Range

The Python `range()` function can be used to generate sequential values and convert them into a Series.

In [1890]:
numbers = range(1, 6)

series = pd.Series(numbers)

series

0    1
1    2
2    3
3    4
4    5
dtype: int64

#### 8. Creating a Series with Specific Data Type

The `dtype` parameter allows us to control the data type stored inside the Series.

This is important when preparing data for analysis and machine learning.

In [1891]:
values = [1, 2, 3, 4]

series = pd.Series(
    values,
    dtype="float64"
)

series

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

#### 9. Creating a Named Series

A Series can have a name using the `name` parameter.

The name becomes the label of the Series and is useful when the Series represents a column in a DataFrame.

In [1892]:
grades = pd.Series(
    [90, 85, 95],
    name="Student Grades"
)

grades

0    90
1    85
2    95
Name: Student Grades, dtype: int64

### Step 4:  Attribute vs Method

In Pandas objects, we interact with data using attributes and methods.

##### Attribute:
- Stores information about the object
- Does not require parentheses ()

Example:
series.shape


##### Method:
- Performs an operation
- Requires parentheses ()

Example:
series.mean()

In [1893]:
s = pd.Series([10, 20, 30], name="Numbers")

# Attribute - no parentheses, just returns existing info
print(s.dtype)

# Method - has parentheses, calculates something
print(s.mean())

int64
20.0

### The Core Series Attributes

Ten attributes describe a Series without changing or calculating anything new.  
They only report information about the object:

| Attribute | Description |
|-----------|-------------|
| `values` | The data only (usually stored as a NumPy array) |
| `index` | The row labels |
| `dtype` | The data type of the values |
| `name` | The name assigned to the Series |
| `shape` | The dimensions of the Series as a tuple |
| `size` | The total number of elements |
| `ndim` | The number of dimensions (always `1` for a Series) |
| `axes` | The list of axes (only the index for a Series) |
| `empty` | `True` or `False` - whether the Series is empty |
| `hasnans` | `True` or `False` - whether the Series contains missing values |

In [1894]:
students = pd.Series(
    [95, 88, 100],
    index=["Ali", "Sara", "Omar"],
    name="Score"
)

print("Series:")
print(students)

# values: the raw data only, no labels - usually returned as a NumPy array
print("\nValues:", students.values)
print("Type of values:", type(students.values))

# index: the row labels (a special pandas Index object, not a plain list)
print("\nIndex:", students.index)
print("Type of index:", type(students.index))

# dtype: the data type stored inside
print("\nData Type:", students.dtype)

# name: the Series' name (useful when it comes from a DataFrame column)
print("\nName:", students.name)

# shape: dimensions as a tuple - (3,) means "3 elements, 1 dimension"
print("\nShape:", students.shape)

# size: total number of elements (just a number, not a tuple)
print("\nSize:", students.size)

# ndim: number of dimensions - always 1 for a Series
print("\nNdim:", students.ndim)

# axes: returns a list containing the index (Series only has one axis: rows)
print("\nAxes:", students.axes)

# empty: True only if the Series has zero elements
print("\nEmpty:", students.empty)

# hasnans: True if there's at least one missing value (NaN) inside
print("\nHasnans:", students.hasnans)

Series:
Ali      95
Sara     88
Omar    100
Name: Score, dtype: int64

Values: [ 95  88 100]
Type of values: <class 'numpy.ndarray'>

Index: Index(['Ali', 'Sara', 'Omar'], dtype='str')
Type of index: <class 'pandas.Index'>

Data Type: int64

Name: Score

Shape: (3,)

Size: 3

Ndim: 1

Axes: [Index(['Ali', 'Sara', 'Omar'], dtype='str')]

Empty: False

Hasnans: False

#### Seeing `empty` and `hasnans` in Action

These two attributes are easier to understand by comparing an empty 
Series and a normal one, and a Series with missing data vs. one without.

In [1895]:
import numpy as np

# An empty Series
empty_series = pd.Series(dtype=int)
print("Empty series:", empty_series.empty)

# A Series with data
full_series = pd.Series([1, 2, 3])
print("Full series:", full_series.empty)

# A Series containing a missing value (NaN)
with_nan = pd.Series([10, 20, np.nan, 30])
print("Has NaN:", with_nan.hasnans)

# A Series with no missing values
without_nan = pd.Series([10, 20, 30])
print("Has NaN:", without_nan.hasnans)

Empty series: True
Full series: False
Has NaN: True
Has NaN: False

#### Hands-On Exercise: Employee Salaries

Create a Pandas Series representing employee salaries.

Data:

Ali     5000
Sara    7000
Omar    4500
Lina    8000


Requirements:

1. Create the Series using custom index labels.

2. Set the Series name to:
"Employee Salaries"

3. Print the following attributes:

- values
- index
- dtype
- name
- shape
- size
- ndim
- axes
- empty
- hasnans

Answer these questions:

1. How many employees are in the Series?
2. Does the Series contain missing values?
3. What is the dimension of the Series?

In [1896]:
import pandas as pd

# Create a Pandas Series representing employee salaries with custom index labels
salaries = pd.Series(
    [5000, 7000, 4500, 8000],
    index=["Ali", "Sara", "Omar", "Lina"],
    name="Employee Salaries"
)

# Display the Series
salaries

Ali     5000
Sara    7000
Omar    4500
Lina    8000
Name: Employee Salaries, dtype: int64

In [1897]:
# Display the core attributes of the Series

print("Values:")
print(salaries.values)

print("\nIndex:")
print(salaries.index)

print("\nData Type:")
print(salaries.dtype)

print("\nName:")
print(salaries.name)

print("\nShape:")
print(salaries.shape)

print("\nSize:")
print(salaries.size)

print("\nNumber of Dimensions:")
print(salaries.ndim)

print("\nAxes:")
print(salaries.axes)

print("\nIs Empty?")
print(salaries.empty)

print("\nContains Missing Values?")
print(salaries.hasnans)

Values:
[5000 7000 4500 8000]

Index:
Index(['Ali', 'Sara', 'Omar', 'Lina'], dtype='str')

Data Type:
int64

Name:
Employee Salaries

Shape:
(4,)

Size:
4

Number of Dimensions:
1

Axes:
[Index(['Ali', 'Sara', 'Omar', 'Lina'], dtype='str')]

Is Empty?
False

Contains Missing Values?
False

1. How many employees are in the Series?
   
   There are 4 employees because the Series contains 4 values.

2. Does the Series contain missing values?

   No, the Series does not contain missing values because `hasnans` returns False.

3. What is the dimension of the Series?

   The Series has 1 dimension because Pandas Series is a one-dimensional data structure.

### Step 5: Label based Indexing

Pandas Series can be accessed using the labels of its index.

In label based indexing, we select data by the index name,
not by its numerical position.

The index labels can be strings, numbers, dates, or any other hashable values.

In [1898]:
import pandas as pd

scores = pd.Series(
    [85, 90, 78, 92],
    index=["Ali", "Sara", "Omar", "Lina"]
)

print(scores)

print(scores["Sara"]) #Access using label

Ali     85
Sara    90
Omar    78
Lina    92
dtype: int64
90

### Step 6: Position based Indexing

Position based indexing accesses elements using their integer location.

Positions start from zero, similar to Python lists.

The first element has position 0.

In [1899]:
scores = pd.Series(
    [85, 90, 78, 92],
    index=["Ali", "Sara", "Omar", "Lina"]
)
print (scores)
print(" scores[Ali] Means : Give me the value where index label is Ali")
print(scores["Ali"]) 
print("scores.iloc[0] Means : Give me the first element by position ")
print(scores.iloc[0])

Ali     85
Sara    90
Omar    78
Lina    92
dtype: int64
 scores[Ali] Means : Give me the value where index label is Ali
85
scores.iloc[0] Means : Give me the first element by position
85

 ##### .loc[] : Label based Selection

.loc is explicitly used for selecting data using index labels.

It is recommended because it makes the intention clear.

In [1900]:
print (scores.loc["Sara"])

print (scores.loc[["Ali","Omar"]])

print (scores.loc["Ali":"Omar"])

90
Ali     85
Omar    78
dtype: int64
Ali     85
Sara    90
Omar    78
dtype: int64

#### .iloc[] : Position-based Selection

.iloc selects data using integer positions.

It works like normal Python indexing.

In [1901]:
print (scores.iloc[1])

print(scores.iloc[[0,2]])

print (scores.iloc[0:2])

90
Ali     85
Omar    78
dtype: int64
Ali     85
Sara    90
dtype: int64

### Exercise: Student Grades Indexing

Create a Pandas Series:

Ahmed     88

Mona      95

Khaled    76

Sara      91


Tasks:

1. Access Mona using label indexing.
2. Access the first student using position indexing.
3. Use .loc to select Ahmed to Khaled.
4. Use .iloc to select the first three students.
5. Explain the difference between the two slicing results.

In [1902]:
import pandas as pd
grades = pd.Series(
    [88,95,76,91] ,
    index = ["Ahmed" , "Mona" , "Khaled" , "Sara"]
)

#Access Mona using label indexing.
print(grades["Sara"])

#Access the first student using position indexing.
print(grades.loc(0))

#Use .loc to select Ahmed to Khaled.
print(grades.loc["Ahmed" : "Khaled"])

#Use .iloc to select the first three students.
print(grades.iloc[0:3])

91
<pandas.core.indexing._LocIndexer object at 0x0000025467D7E350>
Ahmed     88
Mona      95
Khaled    76
dtype: int64
Ahmed     88
Mona      95
Khaled    76
dtype: int64

### Step 7: Boolean Indexing and Filtering Series

Boolean indexing allows us to filter data based on conditions.

A condition creates a Boolean mask containing `True` and `False` values.
Pandas uses this mask to return only the elements that satisfy the condition.

This concept is very important because the same idea is used later when filtering rows in DataFrames during data cleaning and ML preprocessing.

In [1903]:
import pandas as pd

scores = pd.Series(
    [85, 60, 90, 45, 70],
    index=["Ali", "Sara", "Omar", "Lina", "Ahmad"]
)

scores

Ali      85
Sara     60
Omar     90
Lina     45
Ahmad    70
dtype: int64

#### Creating Boolean Masks

A Boolean mask is a Series with the same index as the original Series.
Each position contains:

- `True` → condition is satisfied
- `False` → condition is not satisfied

The mask itself does not filter data until we use it for indexing.

In [1904]:
mask = scores > 70

mask

Ali       True
Sara     False
Omar      True
Lina     False
Ahmad    False
dtype: bool

#### Filtering Using Boolean Indexing

We can use the Boolean mask inside square brackets `[]`
to select only the values where the condition is True.

In [1905]:
scores[mask]

Ali     85
Omar    90
dtype: int64

#### Filtering Directly With Conditions

Instead of creating a separate mask variable,
we can write the condition directly inside the brackets.

In [1906]:
scores[scores > 70]

Ali     85
Omar    90
dtype: int64

#### Comparison Operators

Boolean filtering supports different comparison operators:

- `>` Greater than
- `<` Less than
- `>=` Greater than or equal
- `<=` Less than or equal
- `==` Equal
- `!=` Not equal

In [1907]:
print("Scores greater than 80:")
print(scores[scores > 80])


print("\nScores less than 60:")
print(scores[scores < 60])


print("\nScores equal to 70:")
print(scores[scores == 70])

Scores greater than 80:
Ali     85
Omar    90
dtype: int64

Scores less than 60:
Lina    45
dtype: int64

Scores equal to 70:
Ahmad    70
dtype: int64

#### Combining Multiple Conditions

We can combine conditions using:

| Operator | Meaning |
|----------|---------|
| `&` | AND |
| `|` | OR |
| `~` | NOT |

Important:
Each condition must be wrapped with parentheses.

In [1908]:
scores[(scores >= 60) & (scores <= 90)]

Ali      85
Sara     60
Omar     90
Ahmad    70
dtype: int64

#### Filtering Categorical Data

Boolean indexing is not limited to numeric values.
We can also filter text categories.

In [1909]:
departments = pd.Series(
    ["AI", "Web", "AI", "Data", "Web"],
    index=["Ali", "Sara", "Omar", "Lina", "Ahmad"]
)

departments

Ali        AI
Sara      Web
Omar       AI
Lina     Data
Ahmad     Web
dtype: str

In [1910]:
departments[departments == "AI"]

Ali     AI
Omar    AI
dtype: str

#### Using isin() For Multiple Values

The `isin()` method checks whether each value exists inside a list.

It is useful when filtering multiple categories.

In [1911]:
departments.isin(["AI", "Data"])

Ali       True
Sara     False
Omar      True
Lina      True
Ahmad    False
dtype: bool

In [1912]:
departments[departments.isin(["AI", "Data"])]

Ali       AI
Omar      AI
Lina    Data
dtype: str

### Practice Exercise

Create a Series representing employee salaries.

Tasks:

1. Select employees with salaries above 5000.
2. Select employees with salaries between 3000 and 7000.
3. Select employees whose salary is not equal to 4000.
4. Filter employees with specific salary values using `isin()`.

In [1913]:
salaries = pd.Series(
    [5000 ,7000,3000,2500,8000] , 
    index = ["Nadeen" , "Basel" , "Ali" , "Sara" ,"Omar"]
)

print(salaries)

#Select employees with salaries above 5000.
print(salaries[salaries>5000])

#Select employees with salaries between 3000 and 7000. 
print(salaries[(salaries >= 3000) & (salaries <= 7000)])

# Select employees whose salary is not equal to 4000.
print(salaries[salaries!=4000])

#Filter employees with specific salary values using `isin()`.
print(salaries[salaries.isin([3000, 8000])])

Nadeen    5000
Basel     7000
Ali       3000
Sara      2500
Omar      8000
dtype: int64
Basel    7000
Omar     8000
dtype: int64
Nadeen    5000
Basel     7000
Ali       3000
dtype: int64
Nadeen    5000
Basel     7000
Ali       3000
Sara      2500
Omar      8000
dtype: int64
Ali     3000
Omar    8000
dtype: int64

### Step 8: Boolean Indexing and Fancy Indexing in Pandas Series

#### Boolean Indexing

Boolean indexing allows us to filter data based on conditions.

Instead of selecting values by their labels or positions,
we create a boolean mask that contains True/False values.

Only elements where the condition is True will be returned.

Example:
- Select students with scores greater than 80
- Select employees with salaries above a threshold


#### Fancy Indexing

Fancy indexing means selecting multiple elements by providing
a list of labels or positions.

It allows us to extract multiple values at once.

Example:
- Select specific employees
- Select specific indexes from a Series

In [1914]:
import pandas as pd

# Create a Series
scores = pd.Series(
    [85, 90, 78, 92, 65],
    index=["Ali", "Sara", "Omar", "Lina", "Ahmad"]
)

print(scores)


# -------------------------------
# Boolean Indexing
# -------------------------------

# Create a boolean mask
high_scores = scores > 80

print(high_scores)


# Use mask to filter values
print(scores[high_scores])


# Direct filtering
print(scores[scores >= 90])


# Multiple conditions
# Students with score between 80 and 95

print(scores[(scores >= 80) & (scores <= 95)])



# -------------------------------
# Fancy Indexing
# -------------------------------

# Select multiple labels
selected_students = scores[
    ["Ali", "Lina", "Ahmad"]
]

print(selected_students)

Ali      85
Sara     90
Omar     78
Lina     92
Ahmad    65
dtype: int64
Ali       True
Sara      True
Omar     False
Lina      True
Ahmad    False
dtype: bool
Ali     85
Sara    90
Lina    92
dtype: int64
Sara    90
Lina    92
dtype: int64
Ali     85
Sara    90
Lina    92
dtype: int64
Ali      85
Lina     92
Ahmad    65
dtype: int64

### Step 9: Series Modification and Alignment

#### Series Modification

Pandas Series are mutable.
We can modify existing values,
add new values,
or delete elements.

#### Alignment

One of the strongest features of Pandas is automatic alignment.

When performing operations between Series,
Pandas matches values based on index labels,
not their positions.

This prevents many data analysis mistakes.

In [1915]:
import pandas as pd


sales_2025 = pd.Series(
    [100, 200, 300],
    index=["Jan", "Feb", "Mar"]
)


# Modify existing value
sales_2025["Jan"] = 150


# Add new value
sales_2025["Apr"] = 400


print(sales_2025)



# -------------------------------
# Alignment
# -------------------------------


sales_company_A = pd.Series(
    [100,200,300],
    index=["Jan","Feb","Mar"]
)


sales_company_B = pd.Series(
    [50,70,100],
    index=["Feb","Mar","Apr"]
)



# Pandas aligns using labels

total_sales = sales_company_A + sales_company_B


print(total_sales)

Jan    150
Feb    200
Mar    300
Apr    400
dtype: int64
Apr      NaN
Feb    250.0
Jan      NaN
Mar    370.0
dtype: float64

### Step 10: Arithmetic Operations and Universal Functions

Pandas supports arithmetic operations directly on Series.

Operations are performed element-wise.

Examples:
- Addition
- Subtraction
- Multiplication
- Division


#### Universal Functions (ufuncs)

ufuncs are NumPy functions that operate on every element
of a Series efficiently.

Examples:
- np.sqrt()
- np.exp()
- np.log()

In [1916]:
import pandas as pd
import numpy as np


numbers = pd.Series(
    [1,4,9,16],
    index=["A","B","C","D"]
)


# Arithmetic operations

print(numbers + 5)

print(numbers * 2)

print(numbers / 2)



# NumPy ufuncs

print(np.sqrt(numbers))


print(np.power(numbers,2))


print(np.log(numbers))

A     6
B     9
C    14
D    21
dtype: int64
A     2
B     8
C    18
D    32
dtype: int64
A    0.5
B    2.0
C    4.5
D    8.0
dtype: float64
A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64
A      1
B     16
C     81
D    256
dtype: int64
A    0.000000
B    1.386294
C    2.197225
D    2.772589
dtype: float64

### Step 10: Statistical Methods, Unique Values and Sorting

Pandas provides many methods for understanding data quickly.

#### Statistical Methods

Examples:
- mean()
- median()
- min()
- max()
- sum()
- std()


#### Unique Values

unique() returns all different values.

#### Value Counts

value_counts() counts frequency of each value.

#### Sorting

sort_values() sorts based on values.

sort_index() sorts based on index labels.

In [1917]:
import pandas as pd


grades = pd.Series(
    [90,80,90,70,80,100],
    index=[
        "Ali",
        "Sara",
        "Omar",
        "Lina",
        "Ahmad",
        "Mona"
    ]
)


# -------------------
# Statistics
# -------------------

print(grades.mean())

print(grades.max())

print(grades.min())

print(grades.std())



# -------------------
# Unique values
# -------------------

print(grades.unique())



# Count occurrences

print(grades.value_counts())



# -------------------
# Sorting
# -------------------

print(grades.sort_values())


print(grades.sort_values(ascending=False))


print(grades.sort_index())

85.0
100
70
10.488088481701515
[ 90  80  70 100]
90     2
80     2
70     1
100    1
Name: count, dtype: int64
Lina      70
Sara      80
Ahmad     80
Ali       90
Omar      90
Mona     100
dtype: int64
Mona     100
Ali       90
Omar      90
Sara      80
Ahmad     80
Lina      70
dtype: int64
Ahmad     80
Ali       90
Lina      70
Mona     100
Omar      90
Sara      80
dtype: int64

### Step 11: Missing Values, Reindexing, Apply and astype

Real-world datasets often contain missing values.

Pandas provides tools to detect and handle missing data.

#### Missing Values

Functions:
- isnull()
- notnull()
- fillna()
- dropna()


#### Reindexing

Changes the order of indexes
or adds new indexes.


#### Apply

Apply a custom function to every element.


#### astype

Convert data types.

In [1918]:
import pandas as pd


ages = pd.Series(
    [20,25,None,30],
    index=["Ali","Sara","Omar","Lina"]
)


# Detect missing values

print(ages.isnull())


# Fill missing values

ages = ages.fillna(ages.mean())

print(ages)



# Reindex

new_order = ["Lina","Ali","Sara","Omar"]

print(ages.reindex(new_order))



# Apply function

print(
    ages.apply(lambda x: x+1)
)



# Convert datatype

print(
    ages.astype(int)
)

Ali     False
Sara    False
Omar     True
Lina    False
dtype: bool
Ali     20.0
Sara    25.0
Omar    25.0
Lina    30.0
dtype: float64
Lina    30.0
Ali     20.0
Sara    25.0
Omar    25.0
dtype: float64
Ali     21.0
Sara    26.0
Omar    26.0
Lina    31.0
dtype: float64
Ali     20
Sara    25
Omar    25
Lina    30
dtype: int64

#### Step 12: String and Datetime Operations

Pandas provides specialized tools for handling text and dates.

#### String Operations

Using .str we can:
- lowercase
- uppercase
- split text
- search inside strings


#### Datetime Operations

Using pd.to_datetime()
we convert strings into datetime objects.

Then we can extract:
- year
- month
- day

In [1919]:
import pandas as pd


names = pd.Series(
    [
        "Ali Ahmed",
        "Sara Khaled",
        "Omar Hassan"
    ]
)


# String operations

print(names.str.lower())

print(names.str.upper())

print(names.str.split())

print(names.str.contains("Ali"))



# -----------------------
# Datetime
# -----------------------


dates = pd.Series(
    [
        "2026-01-10",
        "2026-02-15",
        "2026-03-20"
    ]
)


dates = pd.to_datetime(dates)


print(dates)


# Extract information

print(dates.dt.year)

print(dates.dt.month)

print(dates.dt.day)

0      ali ahmed
1    sara khaled
2    omar hassan
dtype: str
0      ALI AHMED
1    SARA KHALED
2    OMAR HASSAN
dtype: str
0      [Ali, Ahmed]
1    [Sara, Khaled]
2    [Omar, Hassan]
dtype: object
0     True
1    False
2    False
dtype: bool
0   2026-01-10
1   2026-02-15
2   2026-03-20
dtype: datetime64[us]
0    2026
1    2026
2    2026
dtype: int32
0    1
1    2
2    3
dtype: int32
0    10
1    15
2    20
dtype: int32

# Pandas DataFrame

### Step 13: What is a DataFrame?

A DataFrame is the main data structure in Pandas used for working with
tabular data.

A DataFrame represents data in a table format similar to:

- Excel spreadsheets
- SQL tables
- CSV files

It consists of:

- Rows → observations / records
- Columns → features / variables
- Index → row labels

Unlike a Series which represents a single labeled column,
a DataFrame represents a complete dataset containing multiple columns.

Example:

Employee Dataset:

| Index | Name | Age | Salary |
|------|------|-----|--------|
| 0 | Ali | 25 | 5000 |
| 1 | Sara | 30 | 7000 |
| 2 | Omar | 28 | 6000 |


In Machine Learning:

- Each row usually represents one sample.
- Each column usually represents one feature.
- The target column represents what we want to predict.

### Series vs DataFrame

#### Series

A Series is a one-dimensional labeled array.

It contains:

- Values
- Index labels


Example:

Age Series:

| Index | Age |
|------|-----|
| Ali | 25 |
| Sara | 30 |


#### DataFrame

A DataFrame is a two-dimensional labeled data structure.

It contains:

- Multiple Series
- Rows
- Columns


Example:

Employee DataFrame:

| Name | Age | Salary |
|-----|-----|--------|
| Ali | 25 | 5000 |
| Sara | 30 | 7000 |


Relationship:

A DataFrame is basically a collection of Series objects
sharing the same index.

DataFrame = Multiple Series + Common Index

In [1920]:
# Import pandas library

import pandas as pd


# Creating a simple DataFrame

employees = pd.DataFrame(
    {
        "Name": ["Ali", "Sara", "Omar"],
        "Age": [25, 30, 28],
        "Salary": [5000, 7000, 6000]
    }
)


# Display DataFrame

employees

   Name  Age  Salary
0   Ali   25    5000
1  Sara   30    7000
2  Omar   28    6000

### Step 14: Understanding DataFrame Structure

A DataFrame contains three main components:

#### 1. Index

The index identifies each row.

By default Pandas creates an integer index:

0,1,2,...

Example:

Row 0 represents the first employee.


#### 2. Columns

Columns represent variables/features.

In Machine Learning:

Columns are usually the input features.


Example:

Age
Salary


#### 3. Values

The actual stored data.

Example:

25
7000

In [1921]:
# Access DataFrame components


# Get the values as NumPy array

print("Values:")
print(employees.values)



# Get row index

print("\nIndex:")
print(employees.index)



# Get column names

print("\nColumns:")
print(employees.columns)

Values:
[['Ali' 25 5000]
 ['Sara' 30 7000]
 ['Omar' 28 6000]]

Index:
RangeIndex(start=0, stop=3, step=1)

Columns:
Index(['Name', 'Age', 'Salary'], dtype='str')

### Step 15: Creating DataFrame from Dictionary

One of the most common ways to create a DataFrame
is using a dictionary.

Dictionary keys become:

→ Column names


Dictionary values become:

→ Column values


Example:

{
"Name": ["Ali","Sara"],
"Age": [20,21]
}


will create:

| Name | Age |
|---|---|
| Ali |20|
|Sara|21|

In [1922]:
# Creating DataFrame from dictionary

student_data = {
    "Student": ["Ahmad", "Lina", "Noor"],
    "Major": ["CS", "AI", "SE"],
    "Grade": [90, 95, 88]
}


students = pd.DataFrame(student_data)


students

  Student Major  Grade
0   Ahmad    CS     90
1    Lina    AI     95
2    Noor    SE     88

### Step 16: Creating DataFrame from List of Dictionaries

Another common method is using a list of dictionaries.

This format is very common when:

- Reading JSON data
- Working with APIs
- Collecting records


Each dictionary represents one row.

Example:

[
 {"Name":"Ali","Age":20},
 {"Name":"Sara","Age":21}
]

Pandas automatically converts each dictionary
into a DataFrame row.

In [1923]:
# List of dictionaries

records = [
    {
        "Name": "Ali",
        "Age": 20,
        "Department": "AI"
    },
    
    {
        "Name": "Sara",
        "Age": 22,
        "Department": "CS"
    }
]


# Convert to DataFrame

df_records = pd.DataFrame(records)


df_records

   Name  Age Department
0   Ali   20         AI
1  Sara   22         CS

### Step 17: Creating DataFrame from NumPy Array

Since Pandas is built on top of NumPy,
we can create DataFrames from NumPy arrays.

When using arrays:

- We usually need to provide column names manually.

In [1924]:
import numpy as np


# Create NumPy array

data = np.array(
    [
        [1, 90],
        [2, 85],
        [3, 95]
    ]
)


# Convert NumPy array to DataFrame

grades = pd.DataFrame(
    data,
    columns=["Student_ID", "Grade"]
)


grades

   Student_ID  Grade
0           1     90
1           2     85
2           3     95

### Step 18: Creating DataFrame from Series

Since a DataFrame is a collection of Series,
we can combine multiple Series together.

Each Series becomes a column.

In [1925]:
# Create Series objects

names = pd.Series(
    ["Ali", "Sara", "Omar"]
)


ages = pd.Series(
    [25, 30, 28]
)


# Combine Series into DataFrame

people = pd.DataFrame(
    {
        "Name": names,
        "Age": ages
    }
)


people

   Name  Age
0   Ali   25
1  Sara   30
2  Omar   28

### Important Notes

#### DataFrame in Machine Learning

A DataFrame is usually the first object we create
after loading a dataset.

Typical ML workflow:

1. Load data
2. Inspect DataFrame
3. Clean missing values
4. Select features
5. Transform data
6. Train model


Understanding DataFrames is essential because
almost every real-world dataset arrives as a table.

### Step 19: Pandas DataFrame Attributes

A DataFrame in Pandas has built-in attributes that provide information
about the structure and properties of the dataset.

Attributes are different from methods:

- Attributes → Give information about the object (No parentheses)
- Methods → Perform actions on the object (Need parentheses)

In [1926]:

import pandas as pd

# Create Example DataFrame


# We create a small dataset to practice DataFrame attributes

employees = pd.DataFrame(
    {
        "Name": ["Ali", "Sara", "Omar"],
        "Age": [25, 30, 28],
        "Department": ["AI", "CS", "SE"],
        "Salary": [5000, 7000, 6000]
    }
)


# Display original DataFrame

print("Original DataFrame:")
print(employees)



# =====================================================
# 1. values
# =====================================================

# Returns only the data values
# without index and column names

print("\n1. DataFrame Values:")
print(employees.values)



# =====================================================
# 2. index
# =====================================================

# Returns row labels

print("\n2. DataFrame Index:")
print(employees.index)



# =====================================================
# 3. columns
# =====================================================

# Returns column names

print("\n3. DataFrame Columns:")
print(employees.columns)



# =====================================================
# 4. dtypes
# =====================================================

# Shows the data type of each column

print("\n4. Data Types:")
print(employees.dtypes)



# =====================================================
# 5. shape
# =====================================================

# Returns:
# (number of rows, number of columns)

print("\n5. DataFrame Shape:")
print(employees.shape)



# =====================================================
# 6. size
# =====================================================

# Returns total number of elements
# rows * columns

print("\n6. DataFrame Size:")
print(employees.size)



# =====================================================
# 7. ndim
# =====================================================

# Returns number of dimensions
# DataFrame is always 2D

print("\n7. Number of Dimensions:")
print(employees.ndim)



# =====================================================
# 8. axes
# =====================================================

# Returns:
# [Index, Columns]

print("\n8. DataFrame Axes:")
print(employees.axes)



# =====================================================
# 9. empty
# =====================================================

# Checks if DataFrame contains data

print("\n9. Is DataFrame Empty?")
print(employees.empty)



# Creating an empty DataFrame

empty_df = pd.DataFrame()


print("\nEmpty DataFrame Check:")
print(empty_df.empty)



# =====================================================
# 10. T (Transpose)
# =====================================================

# Converts rows into columns
# and columns into rows

print("\n10. Transposed DataFrame:")
print(employees.T)

Original DataFrame:
   Name  Age Department  Salary
0   Ali   25         AI    5000
1  Sara   30         CS    7000
2  Omar   28         SE    6000

1. DataFrame Values:
[['Ali' 25 'AI' 5000]
 ['Sara' 30 'CS' 7000]
 ['Omar' 28 'SE' 6000]]

2. DataFrame Index:
RangeIndex(start=0, stop=3, step=1)

3. DataFrame Columns:
Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')

4. Data Types:
Name            str
Age           int64
Department      str
Salary        int64
dtype: object

5. DataFrame Shape:
(3, 4)

6. DataFrame Size:
12

7. Number of Dimensions:
2

8. DataFrame Axes:
[RangeIndex(start=0, stop=3, step=1), Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')]

9. Is DataFrame Empty?
False

Empty DataFrame Check:
True

10. Transposed DataFrame:
               0     1     2
Name         Ali  Sara  Omar
Age           25    30    28
Department    AI    CS    SE
Salary      5000  7000  6000

### Step 20: Pandas DataFrame Inspection Methods

After creating or loading a DataFrame, the first step in any Data Analysis
or Machine Learning project is to inspect and understand the dataset.

Data inspection helps us understand:

- Dataset structure
- Number of rows and columns
- Data types
- Missing values
- Statistical information
- Memory usage


#### Attributes vs Methods

| Type | Description | Example |
|------|-------------|---------|
| Attribute | Gives information about the DataFrame without performing an action. No parentheses needed. | `df.shape` |
| Method | Performs an operation and returns a result. Requires parentheses. | `df.head()` |



#### Important DataFrame Inspection Methods


| Method | Description | What It Returns | Why We Use It |
|--------|-------------|-----------------|---------------|
| `df.head()` | Displays the first rows of the DataFrame. | First 5 rows by default. | Quickly preview the dataset and understand its structure. |
| `df.tail()` | Displays the last rows of the DataFrame. | Last 5 rows by default. | Check the end of the dataset and confirm data loading. |
| `df.info()` | Provides a complete summary of the DataFrame. | Column names, number of non-null values, data types, and memory usage. | Detect missing values and understand column types. |
| `df.describe()` | Generates statistical summary for numerical columns. | Count, mean, std, min, quartiles, max. | Understand data distribution and detect possible outliers. |
| `df.describe(include="object")` | Generates statistical summary for categorical columns. | Count, unique values, top value, frequency. | Analyze text/category columns. |
| `df.memory_usage()` | Shows memory consumed by each column. | Memory usage in bytes for each column. | Useful for optimizing large datasets. |

In [1927]:
import pandas as pd

# ==========================================================
# Create Example DataFrame
# ==========================================================

# This dataset contains:
# - Numerical columns
# - Categorical columns
# - Missing value example

employees = pd.DataFrame(
    {
        "Name": ["Ali", "Sara", "Omar", "Lina", "Ahmad"],
        "Age": [25, 30, 28, 22, 35],
        "Department": ["AI", "CS", "SE", "AI", "CS"],
        "Salary": [5000, 7000, 6000, 4500, 8000],
        "Experience": [2, 5, 4, 1, None]
    }
)



# Display the original DataFrame

print("Original DataFrame:")
print(employees)



# ==========================================================
# 1. head()
# ==========================================================

# Displays the first 5 rows by default

print("\nFirst rows using head():")
print(employees.head())



# Display first 3 rows

print("\nFirst 3 rows using head(3):")
print(employees.head(3))



# ==========================================================
# 2. tail()
# ==========================================================

# Displays the last 5 rows by default

print("\nLast rows using tail():")
print(employees.tail())



# Display last 2 rows

print("\nLast 2 rows using tail(2):")
print(employees.tail(2))



# ==========================================================
# 3. info()
# ==========================================================

# Shows:
# - Column names
# - Non-null values
# - Data types
# - Memory usage

print("\nDataFrame Information:")
employees.info()



# ==========================================================
# 4. describe()
# ==========================================================

# Generates statistical summary
# for numerical columns

print("\nNumerical Statistical Summary:")
print(employees.describe())



# ==========================================================
# 5. describe(include='object')
# ==========================================================

# Generates statistical summary
# for categorical columns

print("\nCategorical Statistical Summary:")
print(employees.describe(include="object"))



# ==========================================================
# 6. memory_usage()
# ==========================================================

# Shows memory used by every column

print("\nMemory Usage Per Column:")
print(employees.memory_usage())



# Calculate total memory usage

print("\nTotal Memory Usage:")
print(employees.memory_usage().sum())

Original DataFrame:
    Name  Age Department  Salary  Experience
0    Ali   25         AI    5000         2.0
1   Sara   30         CS    7000         5.0
2   Omar   28         SE    6000         4.0
3   Lina   22         AI    4500         1.0
4  Ahmad   35         CS    8000         NaN

First rows using head():
    Name  Age Department  Salary  Experience
0    Ali   25         AI    5000         2.0
1   Sara   30         CS    7000         5.0
2   Omar   28         SE    6000         4.0
3   Lina   22         AI    4500         1.0
4  Ahmad   35         CS    8000         NaN

First 3 rows using head(3):
   Name  Age Department  Salary  Experience
0   Ali   25         AI    5000         2.0
1  Sara   30         CS    7000         5.0
2  Omar   28         SE    6000         4.0

Last rows using tail():
    Name  Age Department  Salary  Experience
0    Ali   25         AI    5000         2.0
1   Sara   30         CS    7000         5.0
2   Omar   28         SE    6000         4.0
3   Lina   22         AI    4500         1.0
4  Ahmad   35         CS    8000         NaN

Last 2 rows using tail(2):
    Name  Age Department  Salary  Experience
3   Lina   22         AI    4500         1.0
4  Ahmad   35         CS    8000         NaN

DataFrame Information:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Department  5 non-null      str
 3   Salary      5 non-null      int64
 4   Experience  4 non-null      float64
dtypes: float64(1), int64(2), str(2)
memory usage: 332.0 bytes

Numerical Statistical Summary:
             Age       Salary  Experience
count   5.000000     5.000000    4.000000
mean   28.000000  6100.000000    3.000000
std     4.949747  1431.782106    1.825742
min    22.000000  4500.000000    1.000000
25%    25.000000  5000.000000    1.750000
50%    28.000000  6000.000000    3.000000
75%    30.000000  7000.000000    4.250000
max    35.000000  8000.000000    5.000000

Categorical Statistical Summary:
       Name Department
count     5          5
unique    5          3
top     Ali         AI
freq      1          2

Memory Usage Per Column:
Index         132
Name           40
Age            40
Department     40
Salary         40
Experience     40
dtype: int64

Total Memory Usage:
332

C:\Users\user\AppData\Local\Temp\ipykernel_13924\4243670615.py:102: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(employees.describe(include="object"))

### Step 21: Pandas DataFrame Selection

Selecting data is one of the most important operations when working with
Pandas DataFrames.

In real-world Data Analysis and Machine Learning projects, we usually need
to select:

- Specific columns (features)
- Specific rows (samples)
- Specific values
- Subsets of data


DataFrame selection allows us to prepare the data before:

- Data cleaning
- Feature engineering
- Model training


---

#### DataFrame Selection Methods


| Selection Type | Syntax | Returns | Purpose |
|---|---|---|---|
| Select one column | `df["column"]` | Series | Select a single feature |
| Select multiple columns | `df[["col1","col2"]]` | DataFrame | Select multiple features |
| Select rows by label | `df.loc[]` | Series/DataFrame | Select using index labels |
| Select rows by position | `df.iloc[]` | Series/DataFrame | Select using numerical positions |
| Select specific value | `df.loc[row,column]` | Single value | Access one cell |
| Slice rows | `df[start:end]` | DataFrame | Select range of rows |

In [1928]:
import pandas as pd

# ==========================================================
# Create Example DataFrame
# ==========================================================

employees = pd.DataFrame(
    {
        "Name": ["Ali", "Sara", "Omar", "Lina", "Ahmad"],

        "Age": [25, 30, 28, 22, 35],

        "Department": ["AI", "CS", "SE", "AI", "CS"],

        "Salary": [5000, 7000, 6000, 4500, 8000]
    }
)


print("Original DataFrame:")
print(employees)


# ==========================================================
# 1. Selecting Single Column
# ==========================================================

# Returns one column as Series

print("\nSelecting Age column:")
print(employees["Age"])


# ==========================================================
# 2. Selecting Multiple Columns
# ==========================================================

# Returns DataFrame containing selected columns

print("\nSelecting Name and Salary columns:")
print(employees[["Name", "Salary"]])



# ==========================================================
# 3. Selecting Rows Using loc
# ==========================================================

# loc uses index labels

print("\nFirst row using loc:")
print(employees.loc[0])


# Selecting specific row and column

print("\nSalary of first employee using loc:")
print(employees.loc[0, "Salary"])


# Selecting multiple rows and columns

print("\nRows 0-2 with Name and Salary:")
print(employees.loc[0:2, ["Name", "Salary"]])

# ==========================================================
# 4. Selecting Rows Using iloc
# ==========================================================

# iloc uses numerical positions

print("\nFirst row using iloc:")
print(employees.iloc[0])


# Selecting specific value

# Row position 0
# Column position 3 (Salary)

print("\nSalary using iloc:")
print(employees.iloc[0,3])


# Selecting rows and columns by positions

print("\nFirst 3 rows and first 2 columns:")
print(employees.iloc[0:3,0:2])


# ==========================================================
# 5. DataFrame Slicing
# ==========================================================

# Basic row slicing

print("\nRows from 0 to 2:")
print(employees[0:3])


# loc slicing includes ending index

print("\nloc slicing:")
print(employees.loc[0:3])

# iloc slicing excludes ending position

print("\niloc slicing:")
print(employees.iloc[0:3])

Original DataFrame:
    Name  Age Department  Salary
0    Ali   25         AI    5000
1   Sara   30         CS    7000
2   Omar   28         SE    6000
3   Lina   22         AI    4500
4  Ahmad   35         CS    8000

Selecting Age column:
0    25
1    30
2    28
3    22
4    35
Name: Age, dtype: int64

Selecting Name and Salary columns:
    Name  Salary
0    Ali    5000
1   Sara    7000
2   Omar    6000
3   Lina    4500
4  Ahmad    8000

First row using loc:
Name           Ali
Age             25
Department      AI
Salary        5000
Name: 0, dtype: object

Salary of first employee using loc:
5000

Rows 0-2 with Name and Salary:
   Name  Salary
0   Ali    5000
1  Sara    7000
2  Omar    6000

First row using iloc:
Name           Ali
Age             25
Department      AI
Salary        5000
Name: 0, dtype: object

Salary using iloc:
5000

First 3 rows and first 2 columns:
   Name  Age
0   Ali   25
1  Sara   30
2  Omar   28

Rows from 0 to 2:
   Name  Age Department  Salary
0   Ali   25         AI    5000
1  Sara   30         CS    7000
2  Omar   28         SE    6000

loc slicing:
   Name  Age Department  Salary
0   Ali   25         AI    5000
1  Sara   30         CS    7000
2  Omar   28         SE    6000
3  Lina   22         AI    4500

iloc slicing:
   Name  Age Department  Salary
0   Ali   25         AI    5000
1  Sara   30         CS    7000
2  Omar   28         SE    6000

### Step 22: Missing Values & Data Cleaning

Real-world data is rarely perfect - it often has missing values, exact 
duplicate rows, and columns stored as the wrong data type. Cleaning is 
usually the largest part of any data project, and everything downstream 
depends on doing it correctly.

**Detecting missing values:** `.isnull()` (same as `.isna()`) returns a 
True/False grid marking every missing cell. Combined with `.sum()`, it 
gives a quick count of missing values per column.

**Handling missing values - two strategies:**
- `.dropna()` removes any row containing at least one missing value. 
  Simple, but you lose data - only safe when missing rows are rare.
- `.fillna(value)` replaces missing values instead of removing rows. The 
  replacement value depends on the column type:
  - Numeric columns: fill with the **mean** or **median**
  - Categorical columns: fill with the **mode** (most frequent value) or 
    a constant like `"Unknown"`
  - Time-ordered data: `.ffill()` (carries the last known value forward) 
    or `.bfill()` (pulls the next known value backward)

**Duplicates:** `.duplicated()` flags rows that are exact copies of an 
earlier row (True = duplicate). `.drop_duplicates()` removes them, 
keeping only the first occurrence by default.

**Type conversion:** `.astype(type)` converts a column to a different 
data type (e.g., int to float) - important because some operations 
require a specific type to work correctly.

**Replacing specific values:** `.replace(old, new)` swaps out a specific 
value everywhere it appears in a column - useful for standardizing 
inconsistent category labels (e.g., "AI" → "Artificial Intelligence").

In [1929]:
import pandas as pd
import numpy as np

# A small dataset with an intentional missing Age, missing Department,
# and one exact duplicate row (Ali appears twice, identically)
employees = pd.DataFrame({
    "Name": ["Ali", "Sara", "Omar", "Lina", "Ahmad", "Noor", "Ali"],
    "Age": [25, 30, 28, 22, 35, np.nan, 25],
    "Department": ["AI", "CS", "SE", "AI", "CS", None, "AI"],
    "Salary": [5000, 7000, 6000, 4500, 8000, 5500, 5000]
})
print("Original data:")
print(employees)

# --- 1. Detecting missing values ---
# isnull() returns True/False for every cell; .sum() counts True per column
print("\nMissing values per column:")
print(employees.isnull().sum())

# --- 2. dropna() - remove any row with at least one missing value ---
print("\nAfter dropna():")
print(employees.dropna())

# --- 3. fillna() - fill instead of removing ---
# Numeric column -> fill with the mean
age_filled = employees["Age"].fillna(employees["Age"].mean())
print("\nAge filled with mean:")
print(age_filled)

# Categorical column -> fill with the mode (most common value)
dept_filled = employees["Department"].fillna(employees["Department"].mode()[0])
print("\nDepartment filled with mode:")
print(dept_filled)

# Or fill with a constant placeholder instead
print("\nDepartment filled with a constant:")
print(employees["Department"].fillna("Unknown"))

# Forward fill / backward fill - useful for ordered/time-series data
print("\nAge with forward fill:")
print(employees["Age"].ffill())
print("\nAge with backward fill:")
print(employees["Age"].bfill())

# --- 4. Duplicates ---
print("\nWhich rows are duplicates:")
print(employees.duplicated())

print("\nAfter drop_duplicates():")
print(employees.drop_duplicates())

# --- 5. Type conversion ---
print("\nSalary converted to float:")
print(employees["Salary"].astype(float))

# --- 6. Replacing specific values ---
print("\nStandardizing 'AI' to a full label:")
print(employees["Department"].replace("AI", "Artificial Intelligence"))

Original data:
    Name   Age Department  Salary
0    Ali  25.0         AI    5000
1   Sara  30.0         CS    7000
2   Omar  28.0         SE    6000
3   Lina  22.0         AI    4500
4  Ahmad  35.0         CS    8000
5   Noor   NaN        NaN    5500
6    Ali  25.0         AI    5000

Missing values per column:
Name          0
Age           1
Department    1
Salary        0
dtype: int64

After dropna():
    Name   Age Department  Salary
0    Ali  25.0         AI    5000
1   Sara  30.0         CS    7000
2   Omar  28.0         SE    6000
3   Lina  22.0         AI    4500
4  Ahmad  35.0         CS    8000
6    Ali  25.0         AI    5000

Age filled with mean:
0    25.0
1    30.0
2    28.0
3    22.0
4    35.0
5    27.5
6    25.0
Name: Age, dtype: float64

Department filled with mode:
0    AI
1    CS
2    SE
3    AI
4    CS
5    AI
6    AI
Name: Department, dtype: str

Department filled with a constant:
0         AI
1         CS
2         SE
3         AI
4         CS
5    Unknown
6         AI
Name: Department, dtype: str

Age with forward fill:
0    25.0
1    30.0
2    28.0
3    22.0
4    35.0
5    35.0
6    25.0
Name: Age, dtype: float64

Age with backward fill:
0    25.0
1    30.0
2    28.0
3    22.0
4    35.0
5    25.0
6    25.0
Name: Age, dtype: float64

Which rows are duplicates:
0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

After drop_duplicates():
    Name   Age Department  Salary
0    Ali  25.0         AI    5000
1   Sara  30.0         CS    7000
2   Omar  28.0         SE    6000
3   Lina  22.0         AI    4500
4  Ahmad  35.0         CS    8000
5   Noor   NaN        NaN    5500

Salary converted to float:
0    5000.0
1    7000.0
2    6000.0
3    4500.0
4    8000.0
5    5500.0
6    5000.0
Name: Salary, dtype: float64

Standardizing 'AI' to a full label:
0    Artificial Intelligence
1                         CS
2                         SE
3    Artificial Intelligence
4                         CS
5                        NaN
6    Artificial Intelligence
Name: Department, dtype: str

### Step 23: GroupBy - Split, Apply, Combine

`groupby()` is one of the most powerful Pandas operations. The idea is 
"split-apply-combine": split the data into groups based on a column's 
values, apply an aggregation (mean, sum, count...) to each group 
separately, then combine the results into one summary.

**Basic groupby:** `df.groupby("column")["other_column"].mean()` groups 
rows by a category and computes the mean for each group.

**`.agg()`:** Instead of one statistic, `.agg([...])` computes several 
at once (mean, min, max, count...) in a single call. You can also pass a 
dictionary to apply a *different* aggregation to each column.

**Grouping by multiple columns:** Passing a list `["col1", "col2"]` 
groups by the combination of both columns - useful for more detailed 
breakdowns (e.g., department AND seniority level).

**`.size()` vs. `.count()`:** `.size()` counts all rows in each group 
(including missing values). `.count()` counts only non-missing values in 
a specific column - the two can differ if that column has NaNs.

**`.transform()`:** Unlike `.groupby().mean()` (which shrinks the data 
down to one row per group), `.transform()` broadcasts the group result 
back to match the original DataFrame's shape - useful for adding a "group 
average" column right next to the original data.

**`.filter()`:** Keeps or drops entire groups based on a condition 
applied to the group as a whole (e.g., "keep only departments whose 
average salary is above some threshold").

In [1930]:
import pandas as pd

employees = pd.DataFrame({
    "Name": ["Ali", "Sara", "Omar", "Lina", "Ahmad", "Noor"],
    "Age": [25, 30, 28, 22, 35, 27],
    "Department": ["AI", "CS", "SE", "AI", "CS", "SE"],
    "Salary": [5000, 7000, 6000, 4500, 8000, 5500]
})
print(employees)

# --- 1. Basic groupby: average salary per department ---
print("\nAverage salary per department:")
print(employees.groupby("Department")["Salary"].mean())

# --- 2. agg(): multiple statistics at once ---
print("\nMultiple stats per department:")
print(employees.groupby("Department")["Salary"].agg(["mean", "min", "max", "count"]))

# --- 3. Different aggregation for different columns ---
print("\nMean salary AND max age per department:")
print(employees.groupby("Department").agg({"Salary": "mean", "Age": "max"}))

# --- 4. Grouping by multiple columns ---
employees["Level"] = ["Junior", "Senior", "Junior", "Junior", "Senior", "Senior"]
print("\nAverage salary per department AND level:")
print(employees.groupby(["Department", "Level"])["Salary"].mean())

# --- 5. size() vs count() ---
print("\nsize() - counts all rows per group:")
print(employees.groupby("Department").size())
print("\ncount() - counts non-missing Salary values per group:")
print(employees.groupby("Department")["Salary"].count())

# --- 6. transform(): add the group average back onto every row ---
employees["dept_avg_salary"] = employees.groupby("Department")["Salary"].transform("mean")
print("\nWith department average added as a new column:")
print(employees)

# --- 7. filter(): keep only groups matching a condition ---
print("\nOnly departments with average salary above 5000:")
print(employees.groupby("Department").filter(lambda x: x["Salary"].mean() > 5000))

    Name  Age Department  Salary
0    Ali   25         AI    5000
1   Sara   30         CS    7000
2   Omar   28         SE    6000
3   Lina   22         AI    4500
4  Ahmad   35         CS    8000
5   Noor   27         SE    5500

Average salary per department:
Department
AI    4750.0
CS    7500.0
SE    5750.0
Name: Salary, dtype: float64

Multiple stats per department:
              mean   min   max  count
Department
AI          4750.0  4500  5000      2
CS          7500.0  7000  8000      2
SE          5750.0  5500  6000      2

Mean salary AND max age per department:
            Salary  Age
Department
AI          4750.0   25
CS          7500.0   35
SE          5750.0   28

Average salary per department AND level:
Department  Level
AI          Junior    4750.0
CS          Senior    7500.0
SE          Junior    6000.0
            Senior    5500.0
Name: Salary, dtype: float64

size() - counts all rows per group:
Department
AI    2
CS    2
SE    2
dtype: int64

count() - counts non-missing Salary values per group:
Department
AI    2
CS    2
SE    2
Name: Salary, dtype: int64

With department average added as a new column:
    Name  Age Department  Salary   Level  dept_avg_salary
0    Ali   25         AI    5000  Junior           4750.0
1   Sara   30         CS    7000  Senior           7500.0
2   Omar   28         SE    6000  Junior           5750.0
3   Lina   22         AI    4500  Junior           4750.0
4  Ahmad   35         CS    8000  Senior           7500.0
5   Noor   27         SE    5500  Senior           5750.0

Only departments with average salary above 5000:
    Name  Age Department  Salary   Level  dept_avg_salary
1   Sara   30         CS    7000  Senior           7500.0
2   Omar   28         SE    6000  Junior           5750.0
4  Ahmad   35         CS    8000  Senior           7500.0
5   Noor   27         SE    5500  Senior           5750.0